### ISSUE TITLE
Builds fail on AppVeyor as memory limit is exhaused

### ISSUE THREAD

**Issue by localheinz** [ergebnis/composer-normalize#137]
#### Steps required to reproduce the problem

1. Run build on AppVeyor

#### Expected Result

* Build passes.

#### Actual Result

* Build fails as it is running out of memory, see https://ci.appveyor.com/project/localheinz/composer-normalize/builds/21212053/job/8af1dta5op5jhy2r:

>vendor/bin/phpunit --configuration=test/Integration/phpunit.xml
>PHPUnit 6.5.13 by Sebastian Bergmann and contributors.
>
>Runtime:       PHP 7.1.25
>Configuration: C:\projects\composer-normalize\test\Integration\phpunit.xml
>
>..................................FFFFF............FFF......PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in C:\projects\composer-normalize\vendor\composer\composer\src\Composer\Json\JsonFile.php on line 270
>
>Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**Comment by kaystrobach** [comment]
Typically you would use composer install during ci. This needs a lot less memory. But i understand your goal, which should use composer update.
