### ISSUE TITLE
Enhancement: Show more information about why composer.json is regarded as invalid

### ISSUE THREAD

**Issue by localheinz** [ergebnis/composer-normalize#14]
#### Steps required to reproduce the problem

1. run `composer normalize` in a project with an invalid `composer.json`

#### Expected Result

* information should be output about which part of `composer.json` is invalid

#### Actual Result

* generic message is shown that `composer.json` is invalid

💁‍♂️ For reference, see https://twitter.com/coderabbi/status/952913836595712000.

**Comment by soullivaneuh** [comment]
Why not suggesting composer-lint? :-)

https://packagist.org/packages/sllh/composer-lint

**Comment by localheinz** [comment]
@coderabbi

I will work on this tomorrow!
