### ISSUE TITLE
Consider un-deprecating the file argument

### ISSUE THREAD

**Issue by marcmascort** [ergebnis/composer-normalize#165]
After reading issues #143 and #144 we believe is an error remove file argument.

We have a library to include in our developing projects that require all used packages to develop (lint, stan, ...), and composer normalize is one of these libraries.
With these method, we don't install composer normalize plugin globally, and only install on the project. Our development project has *submodules*, and we normalize submodules composer.json files from project composer using the argument file.
Without the argument file, and using `--working-dir` attribute of composer is impossible for us, use the composer normalize on submodules.
Removing the file attribute, force all developers to install normalize globally.

Please, could you reconsider deprecate file argument?

Thanks!

**Comment by localheinz** [comment]
@marcmascort 

Thank you for bringing this to my attention! I'll think about it and let you know. 🤓

**Comment by localheinz** [comment]
@marcmascort 

And thanks again, I'm glad you find this project useful! I don't want to make it difficult for anyone using it to keep using it.

👍

**Comment by marcmascort** [comment]
@localheinz If you can view our usage of yours tool: https://github.com/articstudio/php-bin

Thanks for this cool tool!

**Comment by localheinz** [comment]
@marcmascort 

Tagged as [`localheinz/composer-normalize:1.1.2`](https://github.com/localheinz/composer-normalize/releases/tag/1.1.2)!

I'm also reverting the removal of the `file` argument in `master` with #168.

**Comment by marcmascort** [comment]
Thanks!
