### ISSUE TITLE
Grumphp task 

### ISSUE THREAD

**Issue by drupol** [ergebnis/composer-normalize#169]
Hi,

Is there any plan to support phpro/grumphp ?

Thanks

**Comment by localheinz** [comment]
Thank you for asking, @drupol!

I‘m not using ~neither~ it, but I will take a look what supporting ~these~ it will entail!

🤓

**Comment by drupol** [comment]
I did it locally. If you wait a bit, I'll submit the pr :)

**Comment by localheinz** [comment]
@drupol 

Sounds great, keep me posted! 👍

**Comment by drupol** [comment]
I just pushed it on my drupol/php-conventions package, find it here: https://packagist.org/packages/drupol/php-conventions

**Comment by drupol** [comment]
Also trying to push it at work: https://github.com/openeuropa/code-review/pull/76
