### ISSUE TITLE
Original JSON is not valid according to schema

### ISSUE THREAD

**Issue by ilyachase** [ergebnis/composer-normalize#175]
#### Steps required to reproduce the problem

For some reason, normalize package didn't worked against my schema, even it certainly correct (tested on https://www.jsonschemavalidator.net/).
There it is:

```
{
    "description": "Domains management system",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=7.1.0",
        "yiisoft/yii2": "~2.0.14",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "linslin/yii2-curl": "1.2.1",
        "symfony/dom-crawler": "^3.3",
        "symfony/css-selector": "^3.4",
        "mikemadisonweb/yii2-rabbitmq": "^2.0",
        "php-amqplib/php-amqplib": "^2.7",
        "guzzlehttp/guzzle": "~6.0",
        "sabre/xml": "^2.1",
        "yiisoft/yii2-mongodb": "^2.1",
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "ext-sockets": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "^8",
        "symfony/var-dumper": "^4.2"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ],
        "test": "phpunit ./tests"
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        }
    }
}
```

**Comment by etshy** [comment]
I had the same problem today.
I never manually edited the file `composer.json` so I guess it should be valid.

**Comment by iLexN** [comment]
I had the same problem, checked https://getcomposer.org/schema.json, it required 

```
"required": [
    "name",
    "description"
],
``` 

in my case, I don't have a description. after add back the description. it works fine.

**Comment by localheinz** [comment]
@etshy @iLexN @ilyachase 

The problem is the following:

- in [`Localheinz\Json\Normalizer\Validator\SchemaValidator::isValid()`](https://github.com/localheinz/json-normalizer/blob/0.9.0/src/Validator/SchemaValidator.php#L30-L40) we validate according to the original JSON schema
- in [`Composer\Json\JsonFile::validateSchema`](https://github.com/composer/composer/blob/1.7.0/src/Composer/Json/JsonFile.php#L168-L174) a lax validation (no fields are required, additional properties are ok) is performed

I should probably perform a lax validation as well.

**Comment by ilyachase** [comment]
Ok, so I double checked original schema (https://getcomposer.org/schema.json) and my JSON, and I actually don't have `name` in it. So I don't think you should change the code. I should fix my JSON and try again first.
