### ISSUE TITLE
Work when no internet available

### ISSUE THREAD

**Issue by WyriHaximus** [ergebnis/composer-normalize#187]
#### Steps required to reproduce the problem

1. Turn off internet for the device this package is ran on
2. run `composer normalize`

#### Expected Result

* Works when no internet connection

#### Actual Result

* Shows the following error message `Schema URI "https://getcomposer.org/schema.json" does not reference a document that could be read.`

**Comment by WyriHaximus** [comment]
@localheinz ping

**Comment by localheinz** [comment]
Related to #80.

**Comment by localheinz** [comment]
I think both #80 and this issue could be solved by referencing `composer-schema.json` as provided with `composer` itself.

Ideally, we could use `Composer\Json\JsonFile::COMPOSER_SCHEMA_PATH`, see https://github.com/composer/composer/blob/1.9.0/src/Composer/Json/JsonFile.php#L37.

**Comment by localheinz** [comment]
@WyriHaximus 

Can you try

```
$ composer global require localheinz/composer-normalize:dev-feature/schema#1f965d4
```

or

```
$ composer require localheinz/composer-normalize:dev-feature/schema#1f965d4
```

and see if that works for you?

**Comment by WyriHaximus** [comment]
@localheinz awesome, let me help you out where I can in #190 :+1:

**Comment by WyriHaximus** [comment]
@localheinz will do on my commute home after work, which has a pretty nice blackhole to test these kind of things

**Comment by WyriHaximus** [comment]
Can confirm that #190 fixes this issue for me :+1:

**Comment by localheinz** [comment]
Thank you, @WyriHaximus!

**Comment by WyriHaximus** [comment]
Thanks you @localheinz, as a nice bonus it's a lot faster now, even on WiFi :tada:
