### ISSUE TITLE
Feature: Different exit code if composer.json has been changed

### ISSUE THREAD

**Issue by mxr576** [ergebnis/composer-normalize#189]
I would like to validate our composer.json's with this tool as part of our CI workflow but as I can see the command always returns with 0 or 1. It return 0 even if it made changes on the file or not. It only returns 1 if something went wrong.

**Comment by localheinz** [comment]
@mxr576 

Thank you for your report, and apologies for not getting back earlier!

Have you tried using the `--dry-run` option?

![Screen Shot 2019-08-22 at 07 59 16](https://user-images.githubusercontent.com/605483/63489570-c2076c80-c4b2-11e9-9e5a-7061afcd62ce.png)

Also see https://github.com/localheinz/composer-normalize/blob/1.2.0/test/Integration/Command/NormalizeCommandTest.php#L384-L429.

**Comment by mxr576** [comment]
It seems to be working :) Thanks!

**Comment by localheinz** [comment]
Thank you, @mxr576!
