### ISSUE TITLE
Wrong schema file path

### ISSUE THREAD

**Issue by homersimpsons** [ergebnis/composer-normalize#254]
#### Steps required to reproduce the problem

1. `docker run -it php:alpine sh`
2. `cd /home/www-data`
3. `apk add composer`
4. `composer init`
    1. `Package name (<vendor>/<name>) [root/www-data]:` enter: `normalize/normalize`
    2. `Description []:` press enter
    3. `Author [, n to skip]:` enter: `n`
    4. `Minimum Stability []:` press enter
    5. `Package Type (e.g. library, project, metapackage, composer-plugin) []:` press enter
   6. `License []:` press enter
   7. `Would you like to define your dependencies (require) interactively [yes]?` enter: ` n`
    8. `Would you like to define your dev dependencies (require-dev) interactively [yes]?` press enter
    9. `Search for a package:` enter: `localheinz/composer-normalize`
    10.`Enter the version constraint to require (or leave blank to use the latest version):` press enter
    11. `Search for a package:` press enter
    12. `Do you confirm generation [yes]?` press enter
    13. `Would you like to install dependencies now [yes]?` press enter
5. `composer normalize` > Here is the error

#### Expected Result

The file should be found

#### Actual Result

Error because the file is not found :

> Schema URI "file:///usr/share/php/Composer/Json/../../../res/composer-schema.json" does not reference a document that could be read.

#### Additional informations

On my installation the file is located at:

> /usr/share/php/data/Composer/res/composer-schema.json

instead of:

> /usr/share/php/Composer/../../res/composer-schema.json

So i updated https://github.com/localheinz/composer-normalize/blob/abb9645a103238c84a06e7cfacb41c289ce09cd3/src/Command/SchemaUriResolver.php#L37

with the following change

```diff
- '%s/../../../res/composer-schema.json'
+ '%s/../../data/Composer/res/composer-schema.json'
```

**Comment by localheinz** [comment]
I'm thinking that by shipping a PHAR, a lot of problems could disappear. For example, I could just use the path to the schema shipped with the PHAR, then.

What do you think, would you use a PHAR instead of the plugin?

**Comment by homersimpsons** [comment]
@localheinz definitely I do prefer phar for all dev dependencies and checking tools, in fact dependency hell is a real mess there. And this will also benefit for this type of issue. Shipping a docker image could be an alternative too.

I saw a ressource that could be useful: https://www.tomasvotruba.cz/blog/2019/12/02/how-to-box-symfony-app-to-phar-without-killing-yourself/
