### ISSUE TITLE
What's the replacement for `localheinz/composer-normalize`?

### ISSUE THREAD

**Issue by ondrejmirtes** [ergebnis/composer-normalize#266]
#### Steps required to reproduce the problem

1. Install `localheinz/composer-normalize`.
2. Get these messages from Composer:

Package localheinz/json-normalizer is abandoned, you should avoid using it. Use ergebnis/json-normalizer instead.
Package localheinz/json-printer is abandoned, you should avoid using it. Use ergebnis/json-printer instead.
Package localheinz/composer-json-normalizer is abandoned, you should avoid using it. Use ergebnis/composer-json-normalizer instead.

3. Fail to find a replacement for `localheinz/composer-normalize` that wouldn't use abandoned packages.

#### Expected Result

* Be able to find a replacement for this package, for example `ergebnis/composer-normalize`.

#### Actual Result

* No replacement in sight.

Thanks :)

**Comment by localheinz** [comment]
Going to take care of this tomorrow, @ondrejmirtes!

Apologies for the confusion!

**Comment by localheinz** [comment]
@ondrejmirtes 

Closing since a replacement has been provided with [`2.0.2`](https://github.com/ergebnis/composer-normalize/releases/tag/2.0.2).

If you like, I will happily open pull requests for the remaining @phpstan repositories not using this yet.

🤓

**Comment by ondrejmirtes** [comment]
Yes, if you’d be so kind, I’d appreciate it 😊 (You should probably have it automated at this point 😀)
