### ISSUE TITLE
[Proposal] Update composer.json to latest version from the lock

### ISSUE THREAD

**Issue by gmponos** [ergebnis/composer-normalize#313]
Although it seems out of scope.. it would be a very very good addition. Ofc my suggestion is this to be done using a flag.

:)

**Comment by localheinz** [comment]
@gmponos 

I've thought about something like this myself - then I came across https://github.com/malukenho/mcbumpface today.

Is that what you are looking for?

**Comment by gmponos** [comment]
nice thnx
