### ISSUE TITLE
Detect and remove duplicate items

### ISSUE THREAD

**Issue by szepeviktor** [ergebnis/composer-normalize#343]
... in arrays and objects.

e.g. https://github.com/Yoast/wordpress-seo/blob/e5bb958f7f9d7a11a103e62ad8142b06e2ff91b0/composer.json#L53-L55

Would it be possible?

**Comment by szepeviktor** [comment]
@localheinz Do you have any thoughts?

**Comment by szepeviktor** [comment]
btw Are results so dark? 
![kép](https://user-images.githubusercontent.com/952007/73376399-ad2ed080-42bd-11ea-9334-e55a781b8218.png)

**Comment by szepeviktor** [comment]
@localheinz What do you think?

**Comment by localheinz** [comment]
@szepeviktor 

Apologies for the delay!

I might change my mind about this, but for now, I think that this is out of the scope of normalizing.

**Comment by szepeviktor** [comment]
Thank you.
