### ISSUE TITLE
Feature: specifying default options in composer.json's extra section

### ISSUE THREAD

**Issue by aleksblendwerk** [ergebnis/composer-normalize#419]
I would like to assure that when anyone runs `composer normalize` without further parameters it's always acting as if `--indent-size 4` and `--indent-style space` were given as options. (Unless other values for these options have been given on the command line, obviously.)

I have seen in other Composer plugins that they offer to retrieve 'configuration' like that from the `extras` section in `composer.json`. Would come in handy, what do you think?

**Comment by localheinz** [comment]
@aleksblendwerk 

I have though about it before, and @WyriHaximus has requested a similar feature a while ago, too. It increases complexity, so let me think about it!

**Comment by WyriHaximus** [comment]
@aleksblendwerk I did? Yes please! Some projects are now indented with 4 and some with 2 and makes copying harder :(

**Comment by localheinz** [comment]
@aleksblendwerk @WyriHaximus 

Apologies for the delay, but you know how things are: there are so many things that we want to get done, but we lack the time for it.

I have released this feature with [`ergebnis/composer-normalize:2.10.0`](https://github.com/ergebnis/composer-normalize/releases/tag/2.10.0).

I hope you like it!

🤓

**Comment by aleksblendwerk** [comment]
Many thanks, @localheinz! 😇

And no need for apologies at all.

I will include it in my project templates as soon as I've got, err... time!

**Comment by localheinz** [comment]
@aleksblendwerk 

You are much welcome!
