### ISSUE TITLE
Support Windows and macOS

### ISSUE THREAD

**Issue by kubawerlos** [ergebnis/composer-normalize#425]
Hi @localheinz,

would you accept the PR that supports Windows and macOS via Github Actions? It would require changes in the configuration to something similar to [this](https://github.com/kubawerlos/composer-require-better/blob/v1.1.0/.github/workflows/ci.yml#L28).

**Comment by localheinz** [comment]
@kubawerlos 

I'm not sure, to be honest - if I do, that means that support for Windows is given. Personally, I can't think of a scenario where I would want to install Windows and debug issues for this platform in the little spare time that I have.

**Comment by kubawerlos** [comment]
And yet, there was a bug on Windows and you have fixed it very quickly :)

For me supporting the OS with a library which is having good tests coverage (and this library has) is simply making sure all tests pass on that OS. And in extreme case, you can always "debug" via Github Actions.

**Comment by localheinz** [comment]
@kubawerlos 

Let me think about it!

**Comment by jpickwell** [comment]
@kubawerlos, I use this on macOS without issue. Windows might be getting better thanks to the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/) (especially with WSL 2), but I'm unsure of this since I now almost exclusively develop on macOS.

**Comment by localheinz** [comment]
@kubawerlos 

After attempting to fix a few tests failing on Windows I can say with 💯 percent certainty that I have no interest in supporting Windows. I have entirely given up on Windows.
