### ISSUE TITLE
Idea: remove defaults

### ISSUE THREAD

**Issue by kubawerlos** [ergebnis/composer-normalize#444]
Would it be useful to have a flag `--remove-defaults` (or `--no-defaults`) that would remove properties that have default values? Like

```json
{
    "minimum-stability": "stable"
}
```

**Comment by kubawerlos** [comment]
Ping @localheinz for an opinion.

**Comment by localheinz** [comment]
@kubawerlos 

I think that this is out of the scope of `ergebnis/composer-normalize`.

I hope you understand.
