### ISSUE TITLE
Allow skipping composer lock freshness check by introducing new option --no-check-lock

### ISSUE THREAD

**Issue by T2L** [ergebnis/composer-normalize#510]
#### Steps required to reproduce the problem

1. I'm running GrumPHP Composer Normalize task for a project which itself is a Composer template repository, ie composer.lock is not committed
2. Composer Normalize does not allow for skipping composer.lock freshness, but for example, Composer task allows for it - https://github.com/phpro/grumphp/blob/master/doc/tasks/composer.md

#### Expected Result

* New option `--no-check-lock` that will skip freshness check

#### Actual Result

* Composer Normalize always forces lock file to be fresh

**Comment by T2L** [comment]
Wow, that was fast. Thanks, @localheinz

**Comment by localheinz** [comment]
You are welcome, @T2L!
