### ISSUE TITLE
project motiviation

### ISSUE THREAD

**Issue by staabm** [ergebnis/composer-normalize#53]
would be great to if the readme would mention some motivating statements, why one would a normalized composer.json file and what the benefits are of having it.

**Comment by localheinz** [comment]
Thank you for your feedback, @staabm!

I have written a blog post at https://localheinz.com/blog/2018/01/15/normalizing-composer.json/. What do you think, would it suffice to link to the blog post, or would it be better to repeat some of what’s in the post?

**Comment by staabm** [comment]
linking the blogpost for in-detail infos would be great.

IMO in the README I would list at list the most important arguments in a rather short form.
