### ISSUE TITLE
Uncaught TypeError JsonSchema Factory / drop <=0.2

### ISSUE THREAD

**Issue by ScreamingDev** [ergebnis/composer-normalize#57]
#### Steps required to reproduce the problem

1. Go PHP 7.0
2. `composer require --dev localheinz/composer-normalize`
3. `composer`

#### Expected Result

* Usual composer listing

#### Actual Result

* Version 0.2.0 installed
* BADABUM

Fatal error: Uncaught TypeError: Argument 1 passed to JsonSchema\Constraints\Factory::__construct() must be an instance of JsonSchema\Uri\UriRetriever, instance of JsonSchema\SchemaStorage given,

Please drop this version from packagist.org or fix this.

**Comment by localheinz** [comment]
Thank you for reporting, @ScreamingDev!

Will take a look later.

**Comment by localheinz** [comment]
I dropped support for PHP 7.0 in https://github.com/localheinz/composer-normalize/pull/30 because field names that are empty strings are not properly decoded in PHP 7.0. Not sure what the best practice is, should I actually delete older versions from Packagist?

**Comment by ScreamingDev** [comment]
Dunno. I would follow some strategy like:

- Once it is "no longer supported" then it has a hint https://github.com/composer/composer/blob/master/res/composer-schema.json#L513
- A year later I would drop the version on packagist if possible.

Last one is valid for your 0.2.0 because it doesn even work with 7.0 anymore.
