### ISSUE TITLE
Normalize changes the line separator from LF to CRLF on windows

### ISSUE THREAD

**Issue by geerteltink** [ergebnis/composer-normalize#58]
#### Steps required to reproduce the problem

1. Check out project with forced LF line separators on Windows
2. run composer normalize

#### Expected Result

* composer.json should keep its original line separators

#### Actual Result

* The line separator changed from LF to CRLF in composer.json

**Comment by localheinz** [comment]
@xtreamwayz 

Can you do me a big favor and take a look at #62, and let me know if this works for you?

I would appreciate it!

🤓

**Comment by geerteltink** [comment]
Works for me!

Thanx.

**Comment by localheinz** [comment]
Glad to hear, @xtreamwayz! I’ll release as soon as possible. 

Thanks a lot for your feedback, taking time to create an issue, and verifying the proposed fix works.
