### ISSUE TITLE
Phar missing from 2.10.0 release

### ISSUE THREAD

**Issue by villfa** [ergebnis/composer-normalize#609]
See:
* https://github.com/ergebnis/composer-normalize/releases/tag/2.10.0
* https://github.com/ergebnis/composer-normalize/runs/1338254999

**Comment by localheinz** [comment]
Apologies, @villfa, I am on it!

**Comment by localheinz** [comment]
@villfa 

Should be fixed now, see https://github.com/ergebnis/composer-normalize/releases/tag/2.10.0:

![CleanShot 2020-11-02 at 09 58 05](https://user-images.githubusercontent.com/605483/97848877-05ce4680-1cf2-11eb-9fc9-4b54b1434f10.png)
