### ISSUE TITLE
Installation fails in fresh project (with no other dependencies)

### ISSUE THREAD

**Issue by faustbrian** [ergebnis/composer-normalize#613]
#### Steps required to reproduce the problem

1. Make a fresh project without any dependencies.
2. Run `composer require ergebnis/composer-normalize` and wait for it to finish.
3. See an error message.

#### Expected Result

Install without errors. Tried on 3 machines and all result in the same issue.

#### Actual Result

```
❯ composer require ergebnis/composer-normalize
Using version ^2.10 for ergebnis/composer-normalize
./composer.json has been created
Running composer update ergebnis/composer-normalize
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires ergebnis/composer-normalize ^2.10 -> satisfiable by ergebnis/composer-normalize[2.10.0].
    - ergebnis/composer-normalize 2.10.0 requires ergebnis/json-printer ^3.1.1 -> found ergebnis/json-printer[dev-main] but it does not match the constraint.


Installation failed, deleting ./composer.json.
```

**Comment by core23** [comment]
I can confirm the issue with the latest (2.0.4) composer version:

```
  Problem 1
    - ergebnis/composer-normalize[2.0.1, ..., 2.3.2] require composer-plugin-api ^1.1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - ergebnis/composer-normalize[2.4.0, ..., 2.6.0] require ergebnis/json-printer ^3.0.2 -> found ergebnis/json-printer[dev-main] but it does not match the constraint.
    - ergebnis/composer-normalize[2.6.1, ..., 2.8.0] require ergebnis/json-printer ^3.1.0 -> found ergebnis/json-printer[dev-main] but it does not match the constraint.
    - ergebnis/composer-normalize[2.8.1, ..., 2.11.0] require ergebnis/json-printer ^3.1.1 -> found ergebnis/json-printer[dev-main] but it does not match the constraint.
    - Root composer.json requires ergebnis/composer-normalize ^2.0.1 -> satisfiable by ergebnis/composer-normalize[2.0.1, ..., 2.11.0].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

**Comment by localheinz** [comment]
@core23 @faustbrian 

Can not reproduce:

```
$ php -v

PHP 7.4.12 (cli) (built: Oct 29 2020 18:37:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies

$ composer --version

Composer version 2.0.6 2020-11-07 11:21:17

$ cd ~/Sites
$ mkdir foo
$ cd foo
$ composer init

# initializing project here

$ composer require --dev ergebnis/composer-normalize

Using version ^2.11 for ergebnis/composer-normalize
./composer.json has been updated
Running composer update ergebnis/composer-normalize
Loading composer repositories with package information
Updating dependencies
Lock file operations: 5 installs, 0 updates, 0 removals
  - Locking ergebnis/composer-normalize (2.11.0)
  - Locking ergebnis/json-normalizer (0.14.0)
  - Locking ergebnis/json-printer (3.1.1)
  - Locking justinrainbow/json-schema (5.2.10)
  - Locking localheinz/diff (1.1.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing localheinz/diff (1.1.1): Extracting archive
  - Installing justinrainbow/json-schema (5.2.10): Extracting archive
  - Installing ergebnis/json-printer (3.1.1): Extracting archive
  - Installing ergebnis/json-normalizer (0.14.0): Extracting archive
  - Installing ergebnis/composer-normalize (2.11.0): Extracting archive
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Changelogs summary:

 - ergebnis/json-printer installed in version 3.1.1
   Release notes: https://github.com/ergebnis/json-printer/releases/tag/3.1.1

 - ergebnis/json-normalizer installed in version 0.14.0
   Release notes: https://github.com/ergebnis/json-normalizer/releases/tag/0.14.0

 - localheinz/diff installed in version 1.1.1
   Release notes: https://github.com/localheinz/diff/releases/tag/1.1.1

 - justinrainbow/json-schema installed in version 5.2.10
   Release notes: https://github.com/justinrainbow/json-schema/releases/tag/5.2.10

 - ergebnis/composer-normalize installed in version 2.11.0
   Release notes: https://github.com/ergebnis/composer-normalize/releases/tag/2.11.0
```

Not sure, perhaps something else is wrong?

**Comment by kubawerlos** [comment]
@core23 @faustbrian have you tried to clear Composer's cache? I got the same issue and clearing cache helped.

**Comment by faustbrian** [comment]
Cleared the cache multiple times and even switched to a machine with a fresh operating system but still persists.

**Comment by localheinz** [comment]
@faustbrian 

Running

```
$ rm -rf ~/.composer
$ cd ~/Sites
$ rm -rf foo
$ mkdir foo
$ cd foo
$ composer require --dev ergebnis/composer-normalize
```

works fine for me.

**Comment by localheinz** [comment]
@faustbrian 

What operating system are you on?

**Comment by core23** [comment]
Some time it works to clear the cache and remove the `composer.lock` file. But the next time I run `composer update` on the same project, it fails with the reported message.

// Running on macOS

**Comment by localheinz** [comment]
@core23 

Can you give me access to a reproducer?

**Comment by faustbrian** [comment]
> @faustbrian
> 
> What operating system are you on?

Catalina and Big Sur

**Comment by localheinz** [comment]
@faustbrian 

Can you share your initial `composer.json`?

**Comment by faustbrian** [comment]
There isn't anything special in my `composer.json` and I can even use your steps from https://github.com/ergebnis/composer-normalize/issues/613#issuecomment-724721163 to run into this issue.

**Comment by WyriHaximus** [comment]
Running into the same issue. Running composer `2.0.7`, with all caches cleared and hard removed right after. Can reproduce it in an empty directory with composer init: 
![Screenshot from 2020-11-16 12-21-46](https://user-images.githubusercontent.com/147145/99247350-1fe64980-2807-11eb-9711-b0748998dde8.png)

**Comment by localheinz** [comment]
@WyriHaximus 

Pressing the **Update** button does not help, but removing the references to

- https://packagist.org/packages/ergebnis/json-printer#dev-dependabot/composer/phpstan/phpstan-0.12.55
- https://packagist.org/packages/ergebnis/json-printer#dev-dependabot/github_actions/gr2m/create-or-update-pull-request-action-v1.3.1

will.

I have experienced this as well, but to me this looks like an issue with `composer` itself, what do you think?

**Comment by WyriHaximus** [comment]
@localheinz 

> I have experienced this as well, but to me this looks like an issue with `composer` itself, what do you think?

Sounds like it, will file an issue with composer if you already haven't

**Comment by localheinz** [comment]
@WyriHaximus 

Thank you!

I will keep the references for now so that @naderman or @seldaek can reproduce.

**Comment by WyriHaximus** [comment]
@localheinz Seems there already is an issue for this: https://github.com/composer/composer/issues/9481

**Comment by Seldaek** [comment]
Wrote up what happened at https://github.com/composer/composer/issues/9481#issuecomment-728328511 - note that removing those refs would not help.. But releasing a new tag would have solved it as it would have redumped the file new and resynced it to mirrors. Thanks for not doing anything rash though which allowed me to fully understand the problem and I now have a good plan on how to avoid this I believe.

**Comment by localheinz** [comment]
Thank you, @Seldaek!

It’s not much, but I’m sending a little joking hazard your way!

😃

**Comment by Seldaek** [comment]
@localheinz thanks ;)
