### ISSUE TITLE
Idea: sort 'patches' alphabetically

### ISSUE THREAD

**Issue by fredden** [ergebnis/composer-normalize#614]
#### Steps required to reproduce the problem
When using `cweagans/composer-patches`, a list of modules is added to a new 'patches' key within 'extra'. This list of packages should be sorted alphabetically.

```json
...
  "extra": {
    "patches": {
      "vendor/package": { ... },
      "another-vendor/module": { ... }
    },
    "patches-ignore": {
      "vendor/package": { ... },
      "another-vendor/module": { ... }
    }
  },
...
```

#### Expected Result
* Lists of packages in extra -> patches and extra -> patches-ignore should be sorted alphabetically.

#### Actual Result
* Lists of packages in extra -> patches and extra -> patches-ignore remains unchanged.

**Comment by localheinz** [comment]
Perhaps it would make sense to keep all entries in `extra` sorted by key when an entry is in object?

**Comment by localheinz** [comment]
@fredden 

Just released as [`ergebnis/composer-normalize:2.12.0`](https://github.com/ergebnis/composer-normalize/releases/tag/2.12.0)!

Let me know how this works for you!

🤓

**Comment by fredden** [comment]
Thanks for this. Unfortunately I'm stuck on composer v1 for some projects, so can't test these changes fully yet. (There's an open issue for composer v1 support: #620.)

**Comment by localheinz** [comment]
@fredden 

Just released support for `composer/composer:^1` as [`ergebnis/composer-normalize:2.13.0`](https://github.com/ergebnis/composer-normalize/releases/tag/2.13.0)!

**Comment by fredden** [comment]
Wow, thanks for such a quick update! I've updated the version used in our continuous integration pipeline and can confirm this is working as expected. Thanks again for picking this up.
