### ISSUE TITLE
Restore Composer 1 support in the 2.x branch

### ISSUE THREAD

**Issue by mxr576** [ergebnis/composer-normalize#620]
Hi,

Today we bumped into an issue because Composer 2 compatibility was suddenly dropped by this plugin and our builds have started to break in those environments where still only Composer 1 is available and we have less control over the installed version.

More information in the related Composer issue: https://github.com/composer/composer/issues/9474

Any chance to rollback [this PR](https://github.com/ergebnis/composer-normalize/pull/597) from the 2.x branch and only drop support of Composer 2 in a new 3.x branch?

**Comment by johnbillion** [comment]
You should be able to address this yourself by using `^2` or `2.9.0` as the version for `ergebnis/composer-normalize`.

**Comment by johnbillion** [comment]
That said, yes this is a breaking change and should have been made in a major release, not a patch release.

**Comment by localheinz** [comment]
@mxr576 

I will think about it, but as an alternative, consider updating `composer` in your build environments.

**Comment by localheinz** [comment]
@johnbillion 

It's not a breaking change, see https://github.com/ergebnis/composer-normalize/pull/597, and in particular, https://github.com/ergebnis/composer-normalize/commit/5413856c3888b104bb9092f9d07ee0abad35cd98#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R21.

**Comment by johnbillion** [comment]
@localheinz Thanks for your work on this extension, it's very useful. Why do you not consider dropping support for Composer v1 as a breaking change?

**Comment by mxr576** [comment]
We do our best to get all envs on Composer 2, but as I wrote above, some environment are not in our control and think we are not the only one.

If Composer would know that it should not update to the latest minor/patch version of this library because it dropped Composer 2 support, this would not be an issue, but it does not know that and it won't, Composer maintainers have no interest to have this supported. (Which is fine.)
I am considering this BC break, because the build tool (aka Composer) cannot handle this change properly, if it would have happened in the major version that would be fine because the version constraint like `^2` or `^2.6` , etc would not allow Composer to upgrade to next major version.

(It is kinda like dropping support of a PHP version in a minor/patch version, which can be considered an edge case, BUT at least Composer can handle it, because it won't install the new version if the runtime environment has an older PHP version than what it is in the `require` section.)

**Comment by localheinz** [comment]
@mxr576 

I need to ask: have you considered sponsoring me to change my mind?

https://github.com/sponsors/localheinz

**Comment by mxr576** [comment]
Originally, I thought about code contribution if restoring Composer 1 compatibility is acceptable, but I'll consider the other option :)

**Comment by localheinz** [comment]
@johnbillion @mxr576 

Released as [`ergebnis/composer-normalize:2.13.0`](https://github.com/ergebnis/composer-normalize/releases/tag/2.13.0)!

**Comment by mxr576** [comment]
Awesome :)
Thank you! :+1:

**Comment by localheinz** [comment]
@mxr576 

You are welcome!
