### ISSUE TITLE
composer-plugin-api should not be alphabetized as a dependency

### ISSUE THREAD

**Issue by danepowell** [ergebnis/composer-normalize#673]
Composer internally treats `composer-plugin-api` as a special dependency (alongside things like `php` or `ext-json`) and always places it ahead of other packages. This conflicts with Composer Normalize, which wants to sort `composer-plugin-api` alphabetically with other dependencies.

#### Steps required to reproduce the problem

1. `composer require composer-plugin-api`
2. `composer require acquia/drupal-environment-detector`
3. `composer require --dev ergebnis/composer-normalize`
4. `composer normalize --dry-run`

#### Expected Result

* Composer Normalize does not complain, since composer.json was build natively by composer and is already sorted correctly:

```
"require": {
  "composer-plugin-api": "^2.0",
  "acquia/drupal-environment-detector": "^1.2"
```

#### Actual Result

* Composer Normalize wants to move acquia/drupal-environment-detector above composer-plugin-api, conflicting with Composer's own sort logic

**Comment by localheinz** [comment]
Thank you for reporting, @danepowell!

Will be fixed with https://github.com/ergebnis/json-normalizer/pull/463. I will let you know when I release both packages!
