### ISSUE TITLE
Composer.json and .lock versions do not match for installed libraries.

### ISSUE THREAD

**Issue by kazajhodo** [ergebnis/composer-normalize#679]
#### Steps required to reproduce the problem

1. Use wikimedia/composer-merge-plugin to install libraries with composer.libraries.json files.

For instance I use:

```json
"merge-plugin": {
            "ignore-duplicates": false,
            "include": [
                "web/modules/contrib/*/composer.libraries.json"
            ],
            "merge-dev": true,
            "merge-extra": false,
            "merge-extra-deep": false,
            "merge-scripts": false,
            "recurse": true,
            "replace": false
        }
```

As configuration. 
This will grab that file and install library deps for a module.

2. When I run composer normalize, and these libraries are included, every library included throws an error, due to a false positive of sorts.

Versions being:
1.18.2.0
vs
1.18.2

ACTUAL ERROR MESSAGE

```
Your requirements could not be resolved to an installable set of packages.

Root composer.json requires x == 1.18.2.0, found x[1.18.2] in lock file but not in remote repositories, make sure you avoid updating this package to keep the one from lock file.

Script composer normalize handling the post-install-cmd event returned with error code 2.
```
END

In the root composer.json... which is inherently the composer.libraries.json from another module... I have a repository defined as:
```json
"x": {
            "type": "package",
            "package": {
                "name": "x",
                "version": "1.18.2",
                "type": "drupal-library",
                "extra": {
                    "installer-name": "x"
                },
                "dist": {
                    "url": "https://registry.npmjs.org/places.js/-/places.js-1.18.2.tgz",
                    "type": "tar"
                },
                "require": {
                    "composer/installers": "~1.0"
                }
            }
        }
```

#### Expected Result

* I expect the version numbers to match and validate.

#### Actual Result

* For some reason I have a 1.18.2.0 in composer.json, 1.18.2 in lock. I think this is a false positive, I only get this error when running composer normalize. The error does stop scripts from running, which is the only reason I've brought it up.

**Comment by kazajhodo** [comment]
Actually, if I have 'composer normalize' as my last script to run, obviously other scripts aren't interrupted. So in that way I can work around this issue- but its probly still a very minor bug that should be resolved.

**Comment by kazajhodo** [comment]
Also had this pop up from a standard composer install, issue may be more related to composer-merge than normalize plugin. Maybe, maybe not.

**Comment by localheinz** [comment]
@kazajhodo 

I do not understand the problem. Can you give me a concrete example, perhaps a repository that reproduces the problem?
