### ISSUE TITLE
Interface 'Localheinz\Json\Normalizer\NormalizerInterface' not found exception

### ISSUE THREAD

**Issue by aviator-ua** [ergebnis/composer-normalize#68]
#### Steps required to reproduce the problem

1. Go PHP 7.1
2. `composer global require localheinz/composer-normalize` 
3. `composer update`

#### Expected Result

* Normal composer update output

#### Actual Result

* `Fatal error: Interface 'Localheinz\Json\Normalizer\NormalizerInterface' not found in /Users/user/.composer/vendor/localheinz/composer-normalize/src/Normalizer/ComposerJsonNormalizer.php on line 20`

**Comment by localheinz** [comment]
@aviator-ua 

Thank you for your report!

I have tried to reproduce the issue, and after deleting my global composer files with

```
$ rm -rf ~/.composer
```

I ran the following steps

```
$ php -v

PHP 7.1.16 (cli) (built: Mar 31 2018 02:28:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16, Copyright (c) 1999-2018, by Zend Technologies

$ composer --version

Composer version 1.6.5 2018-05-04 11:44:59

$ composer global info

Changed current directory to /Users/am/.composer
Composer could not find a composer.json file in /Users/am/.composer
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

$ composer global require localheinz/composer-normalize

Changed current directory to /Users/am/.composer
Using version ^0.8.0 for localheinz/composer-normalize
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing sebastian/diff (3.0.0): Downloading (100%)
  - Installing localheinz/json-printer (2.0.0): Downloading (100%)
  - Installing justinrainbow/json-schema (5.2.7): Downloading (100%)
  - Installing localheinz/json-normalizer (0.6.0): Downloading (100%)
  - Installing localheinz/composer-normalize (0.8.0): Downloading (100%)
Writing lock file
Generating autoload files

$ composer normalize

Composer could not find a composer.json file in /Users/am
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

That is, I have been unable to reproduce the issue.

Can you try again, or maybe also share the output of 

```
$ composer global info --direct
```

?

**Comment by localheinz** [comment]
For reference, @WyriHaximus reported the same issue. 

See 
https://ci.appveyor.com/project/WyriHaximus/client-services/build/job/mnvr1xjqf97rmbob

**Comment by ondrejmirtes** [comment]
I have now the same issue in my Travis build: https://travis-ci.org/phpstan/phpstan/jobs/412048416

**Comment by localheinz** [comment]
@ondrejmirtes 

Taking a look!

**Comment by localheinz** [comment]
@ondrejmirtes 

I have been able to reproduce the issue, running

```
$ git clone git@github.com:phpstan/phpstan.git
$ cd phpstan
$ composer install
$ composer validate
```

yields

```
PHP Fatal error:  Interface 'Localheinz\Json\Normalizer\NormalizerInterface' not found in /Users/am/Sites/phpstan/phpstan/vendor/localheinz/composer-normalize/src/Normalizer/ComposerJsonNormalizer.php on line 20

Fatal error: Interface 'Localheinz\Json\Normalizer\NormalizerInterface' not found in /Users/am/Sites/phpstan/phpstan/vendor/localheinz/composer-normalize/src/Normalizer/ComposerJsonNormalizer.php on line 20
```

Basically, after installing, every `composer` command fails with this error message. Trying to get to the bottom of this!

**Comment by localheinz** [comment]
@ondrejmirtes 

It appears that this is an issue with `composer`, I installed `composer` at https://github.com/composer/composer/tree/1.6.5, and it works fine. Let me find out what it is!

**Comment by localheinz** [comment]
@ondrejmirtes 

~~Opened~~ Spotted an issue at https://github.com/composer/composer/issues/7516.

**Comment by localheinz** [comment]
Possibly fixed by https://github.com/composer/composer/commit/a74b63985e7cd811e5cdde30753249d8466666dd.

**Comment by peter279k** [comment]
After taking a look at this [PR](https://github.com/localheinz/test-util/pull/94), it seems that the latest Composer version has this issue.

**Comment by nicwortel** [comment]
I am running into the same issue after upgrading from Composer 1.6.5 to 1.7.0. Unfortunately I had to manually remove this package in order to get Composer working again.

**Comment by localheinz** [comment]
@nicwortel 

This is an issue in `composer/composer` and has already been fixed with https://github.com/composer/composer/commit/a74b63985e7cd811e5cdde30753249d8466666dd.

As a workaround, follow @Seldaek's suggestion at https://github.com/composer/composer/issues/7516#issuecomment-410459001:

> You can temporarily use `composer self-update --snapshot` to get the fix, I'll release a tag as soon as https://github.com/composer/composer/issues/7517 gets fixed which should be soon enough.

**Comment by WyriHaximus** [comment]
Can confirm that hat fix works 👍

**Comment by localheinz** [comment]
@WyriHaximus 

Great to hear!

For reference, also see https://github.com/localheinz/test-util/pull/94.

**Comment by WyriHaximus** [comment]
@localheinz yeah not really keen on updating all my packages temporary, I'll wait @Seldaek releases the next composer version with this fix in it.

**Comment by WyriHaximus** [comment]
FYI be sure to update composer before restoring cache not after, or the update fails: 
![image](https://user-images.githubusercontent.com/147145/43727423-38b82c4e-99a2-11e8-9ff7-ff40d0f49cef.png)

**Comment by localheinz** [comment]
@WyriHaximus 

Yes, every `composer` command fails, unfortunately.

I apologize for any inconvenience!

**Comment by Seldaek** [comment]
https://github.com/composer/composer/releases/tag/1.7.1 is out now with the fix

**Comment by localheinz** [comment]
Thank you, @seldaek!

**Comment by nicwortel** [comment]
Can confirm that the upgrade to Composer 1.7.1 fixed the issue. Thank you @Seldaek and @localheinz for your work! :+1:

**Comment by localheinz** [comment]
@nicwortel 

You are welcome! Apologies again for any troubles.

**Comment by WyriHaximus** [comment]
Can also confirm that this fixes the issues. Thank you @localheinz and @Seldaek :+1:

**Comment by ondrejmirtes** [comment]
Thanks everyone 😊

**Comment by localheinz** [comment]
Closing!
